autry="http://data.americanartcollaborative.org/autry"
ccma="http://data.americanartcollaborative.org/ccma"
GM="http://data.americanartcollaborative.org/GM"
IMA="http://data.americanartcollaborative.org/ima"
PUAM="http://data.americanartcollaborative.org/puam"
WAM="http://data.americanartcollaborative.org/wam"